name: SimpleAFK
main: andreiwasfound.simpleafk.Main
author: AndreiWasFound
version: 1.0
description: Simple /afk plugin.
website: https://www.spigotmc.org/resources/simpleafk.81963/

commands:
  afk:
    description: Puts you in afk mode
    permission: simpleafk.use